# Generated by Django 4.1.1 on 2022-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('failed', 'failed'), ('success', 'success'), ('pending', 'pending'), ('running', 'running')], default='pending', max_length=30)),
            ],
        ),
    ]
