# Generated by Django 4.1.1 on 2022-10-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_celery_model_count_celery_model_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celery_model',
            new_name='Celery_log',
        ),
    ]
